CA_EMAIL='my@example.com'
CA_EAB_KEY_ID='tcQD1UJV__0-OLQX6KX-_w'
CA_EAB_HMAC_KEY='sJjqLW9ZTll02NPDBS5IXnkUi74xAbtiXLH5PmaIRcm_dhIS9fL3QFmgJDx5enKkquLu81oUKDNQtibd8A4zTg'
ACCOUNT_URL='https://acme.zerossl.com/v2/DV90/account/tcQD1UJV__0-OLQX6KX-_w'
CA_KEY_HASH='PiBKBqgrw+8/a06yX7hkgHlAiha0MTMzlPHLOd7vgZ4='
