Le_Domain='opencv.website'
Le_Alt='no'
Le_Webroot='no'
Le_PreHook=''
Le_PostHook=''
Le_RenewHook=''
Le_API='https://acme.zerossl.com/v2/DV90'
Le_Keylength='ec-256'
Le_OrderFinalize='https://acme.zerossl.com/v2/DV90/order/9J8FajYzp4WPvaYH8FfdHw/finalize'
Le_LinkOrder='https://acme.zerossl.com/v2/DV90/order/9J8FajYzp4WPvaYH8FfdHw'
Le_LinkCert='https://acme.zerossl.com/v2/DV90/cert/Q0TTS4DYwhJjMSQObmc21g'
Le_CertCreateTime='1769497284'
Le_CertCreateTimeStr='2026-01-27T07:01:24Z'
Le_NextRenewTimeStr='2026-02-25T07:01:24Z'
Le_NextRenewTime='1772002884'
Le_RealCertPath=''
Le_RealCACertPath=''
Le_RealKeyPath='/data/opencv.website/privkey.key'
Le_ReloadCmd=''
Le_RealFullChainPath='/data/opencv.website/fullchain.crt'
